### ISSUE TITLE
Fix THM_injection test

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/falcon#14]
The test involves ComputeCappedWeakInclinedPlaneStress.  In MOOSE we are in the process of changing the name of this class and related classes, so soon the THM_injection test will fail.  The fix is straightforward - i'll send a PR once the changes are made in MOOSE.

**Comment by yidongxiainl** [comment]
Good. Thanks.

**Comment by rpodgorney** [comment]
Is this still open?

**Comment by WilkAndy** [comment]
I'm not sure.  I haven't played with falcon for a while.  Certainly if the THM_injection passes then this issue should be closed.

**Comment by rpodgorney** [comment]
THM injection test now passes.
