### ISSUE TITLE
Provide material properties from database

### ISSUE THREAD

**Issue by yidongxiainl** [idaholab/falcon#19]
# Description
Given a group of scattered points in 3D space (usually provided from a database software package, e.g. RockWorks), a tetrahedral mesh (in the format of legacy ascii based VTK) that does not contain material properties can be generated in the toolkit TetGen. The scattered points are the exact mesh nodes. Material properties such as porosity or permeability are initially provided in the point data. What options are there for providing FALCON with the field material properties? Two approaches will be explored and examined.

# Approach 1
Nodal material properties can be appended into the VTK mesh file. The VTK mesh file that contains the nodal material properties can be converted and output to Exodus-II format by using ParaView. The VTK mesh contains the boundary IDs for xmin, xmax, ymin, ymax, zmin, and zmax boundaries . So the final Exodus-II mesh will contain SideSet IDs. The limitation of this approach is that no additional operation is applicable to the Exodus-II mesh containing the nodal material data. Cubit does not read in the nodal attributes of material data. 

# Approach 2
Directly convert the VTK mesh to Exodus-II mesh without imbedding the nodal material properties. This can allow flexibility for any additional operation to the mesh in Cubit, e.g. assign new SideSet IDs. Nodal material data can be read separately into FALCON. **This seems like a better solution to the needs**.

# Summary
The second approach, after implementation and testing, shows best flexibility. The detailed procedure is as blow:

1. Given a group of scatterd nodes with nodal attributes "example.node", use TetGen to generate a tetrahedral mesh in the VTK-format "example.vtk". This VTK mesh does not retain the nodal attributes. So there needs a handy code (written in Python or whatever other programming language) to append the nodal attributes into the VTK mesh, and save the updated "example.vtk" 

2. Load the VTK mesh "example.vtk" (containing nodal attributes) in ParaView, and do save data in Exodus format "example.e". Notice that the nodes in the resulted Exodus mesh are reordered. Load "example.e" in ParaView, and do "save data" in CSV format "example.csv". In this way, the reordered list of nodal attributes is obtained and will be used to provide nodal attributes in a MOOSE-based app.

3. "example.e" does not contain any side-set information. So if side-sets are needed for defining BCs in simulation, load "example.e" in Cubit, and assign side-sets. Do not forget to reset the type of element from "TETRA" to "TETRA4", and save the final "example.e"

**Comment by yidongxiainl** [comment]
Elemental attributes are almost not considered in this scenario, although the feature can be generalized. As a matter of fact, we always just get a group of scatted nodes in 3D space.

**Comment by WilkAndy** [comment]
This could almost be placed on mooseframework.org.  That node renumbering is super annoying!

**Comment by permcody** [comment]
> This could almost be placed on mooseframework.org.  That node renumbering is super annoying!

Funny you say that, you were just using a vector yesterday to store data per element. Imagine a mesh generated through some generation process where several intermediate elements get thrown away so that you have giant holes in your mesh numbering. The renumbering was originally put in so that you could use vectors and have nice continuous numbering. We are starting to run into more and more people that really need us to leave numbering alone. You can control it now through input file parameters, whether we should change the default is up for debate.

**Comment by WilkAndy** [comment]
Yes, you are right, heheheh!  Once you understand re-numbering occurs then it's fine, but before you understand then it's rather confusing!  Presumably Paraview renumbers for the same reason as MOOSE.

**Comment by yidongxiainl** [comment]
Andy, I agree that I can put this development into MOOSE directly. Cody, right?

**Comment by yidongxiainl** [comment]
The downside of the whole workflow from scattered points to Exodus + CSV is that it is not automated. My intern Andy Lau can automate part of it, from the scattered points to the VTK mesh with nodal attributes.

**Comment by permcody** [comment]
There is another approach to this problem. You can always read in your point data independently from the mesh and lookup data from the database. We do this in other projects. We have nanoflann which can build a fast space partitioning search and then you can get the data you need. This removes all of the intermediate stages and other tools that need to do it with the way you've proposed here.

**Comment by WilkAndy** [comment]
The approach can be automated using the python vtk library.  It's a bit of work, but possible.
