### ISSUE TITLE
THM_injection.transient_run has lots of deprecated messages and one error message

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/falcon#22]
Deprecated: PorousFlowInternalEnergyIdeal , PorousFlowEnthalpy , PorousFlow1PhaseP_VG , PorousFlowDensityConstBulk , PorousFlowViscosityConst

Error:
A finite stress material cannot both have an initial stress and an elasticity tensor with varying values; please use a defined constant elasticity tensor, such as ComputeIsotropicElasticityTensor, if your model defines an initial stress, or apply an initial strain instead

Pinging @cpgr and @sapitts .

**Comment by cpgr** [comment]
The deprecated messages are a simple fix. I didn't even know that any porous_flow stuff was used here

**Comment by sapitts** [comment]
@dschwen has a merge request in to address the error (MOOSE [9517](https://github.com/idaholab/moose/pull/9517) )
