### ISSUE TITLE
Clone Falcon

### ISSUE THREAD

**Issue by camlai** [idaholab/falcon#25]
Dear Sir,

I am a very new one use Moose framework and falcon. I clone Falcon by writing the command:
**$ cd ~/projects
$ git clone git@github.com:idaholab/falcon.git**

However, there has this notice:
Cloning into 'falcon'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Could you show me what it was happened and how to solve it?
Thank you so much!
Camlai.

**Comment by yidongxiainl** [comment]
This is not a technical issue. So please do not open an issue ticket related to questions of installation and compilation. Just this once, please read the section of **Generate SSH Keys** on the Falcon project page <https://github.com/idaholab/falcon>. Follow the instructions, and you should be able to do it.
