### ISSUE TITLE
complete documentation

### ISSUE THREAD

**Issue by rpodgorney** [idaholab/falcon#45]
Opening an issue to work on the documentation 

@wjin33 @yidongxiainl @cbolisetti

**Comment by rpodgorney** [comment]
@rpodgorney will handle the general layout and content, @crswong888 will fix a few structural issues.   Everyone else can jump in wherever, with a focus on examples.   Remember simple/easy examples are great to get people going....

@andrsd can you make an example for THM-FALCON (aka Kestrel)?

adding @wilkandy in case he's interested

**Comment by rpodgorney** [comment]
Please have a look at "doco" branch--I added most off of the content, except for the examples

**Comment by rpodgorney** [comment]
adding a pull request #48

**Comment by rpodgorney** [comment]
@crswong888 I need to add a folder and file into the MOOSE large_media submodule.  Not 100% sure of the correct git command sequence.   The folder needs to be called "falcon" and the file is in the doco branch. It's the only mp4 file in there

**Comment by crswong888** [comment]
Done

**Comment by rpodgorney** [comment]
I merged the changes of the base docs pages just now---we just need examples but the docs [ages as is are fit to be published.....how does this happen?

So that https://mooseframework.inl.gov/falcon is a live page?

**Comment by crswong888** [comment]
I actually don't know how to serve the website under this domain but I think @aeslaughter or @loganharbour do.

**Comment by aeslaughter** [comment]
We will need to add recipe to civet to copy the docs to the live page.

**Comment by loganharbour** [comment]
@aeslaughter need me to do it or are you on it?

**Comment by aeslaughter** [comment]
@loganharbour If you have time, I would appreciate the help.

**Comment by rpodgorney** [comment]
addressed by https://github.com/idaholab/falcon/pull/123
