### ISSUE TITLE
"Stochastic" capability

### ISSUE THREAD

**Issue by yidongxiainl** [idaholab/falcon#5]
The capability to model the "stochastic" field is crude. It has to be able to read in external property distributions. Two things within material properties shall be made possible:
1. Tensor based material properties, e.g., permeability.
2. A general property reader as an option in the material kernel, i.e., flag = "default", read from input deck, flag = "external," read from external file

**Comment by permcody** [comment]
Yidong, Have you started on this task? File IO can be tricky as we scale up. To do this properly, you'll really want to read information in on the root processor and broadcast it. This should occur in the `initialSetup()` method. I'm working on a general data structure reader/serializer capability that will probably be in the code base in January. This will be really useful for this task.

**Comment by yidongxiainl** [comment]
Not yet. I will not plan doing it very recently, but this is on our to-do-list. I'll probably start this work after the MOOSE support is ready, as you described. Thanks for your very useful reminder. @permcody
