### ISSUE TITLE
Problem with new THM Test case

### ISSUE THREAD

**Issue by permcody** [idaholab/falcon#9]
https://www.moosebuild.org/branch/59/

@yidongxia

**Comment by permcody** [comment]
Looks like you forget the prereq parameter on the transient part. They are running simultaneously!

**Comment by yidongxiainl** [comment]
Bug fixed.

**Comment by permcody** [comment]
Bug is still there! You need a prereq on the second part of your test.

**Comment by yidongxiainl** [comment]
In my fix commit, I used a pre-existing ExodusII file (thm_transient_ic.e) as input for my second test, so as to make the second test independent of the first test. I forced pushed it to replace the old commit.

But seems Civet still shows the result from the old commit. I will talk to you

**Comment by permcody** [comment]
You haven't pushed according to Github. You may have received an error message or had some other problem but your last commit is dated 2/25.

**Comment by yidongxiainl** [comment]
<https://github.com/idaholab/falcon/commit/49d69cccec5930171d72e9e72cb4cc0f7316c37c> this is not on GitHub?

**Comment by permcody** [comment]
Actually, it looks OK now. Did you say you force pushed to devel?

**Comment by yidongxiainl** [comment]
The original commit to devel caused the issue. Then I pushed an amended commit to devel to override the original one. Maybe this is an illegal action according to the rule?

**Comment by permcody** [comment]
Yeah - you **never** force push to a public branch. The reason is that you can destroy other people's work that way unintentionally and also make it impossible for other to rebase as the hashes can change out from underneath people.

Yeah I know that you are really the only person pushing to Falcon but this is sound advice regardless. I suggest that you develop on Falcon just like you do with the MOOSE repository. Open a PR and let CIVET tell you if everything is OK, then you can merge or have somebody else review and merge.

**Comment by yidongxiainl** [comment]
Yeah that should be my last illegal action. I promise to myself that I will not do that again.
